version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${TARGET_STAGE:-development} # Par défaut, utilise "development"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: ${NODE_ENV:-development}
